import { mkdir, writeFile, readFile, stat } from 'node:fs/promises';
import path from 'node:path';

// A ready-to-play co-op mission ArmaHost writes into the server's MPMissions folder, for people who
// have no missions. mission.sqm only holds playable infantry slots (the part every mission needs);
// everything else (start position, respawn point, Arsenal, Zeus for the logged-in admin) is plain
// SQF using long-stable commands, so it works on any terrain without hand-written editor modules.
export const COOP_WORLDS = [
  { world: 'Altis', label: 'Altis' }, { world: 'Stratis', label: 'Stratis' }, { world: 'Malden', label: 'Malden 2035' },
  { world: 'VR', label: 'Virtual Reality' }, { world: 'Tanoa', label: 'Tanoa (Apex DLC)' }, { world: 'Enoch', label: 'Livonia (Contact DLC)' }
];
export const COOP_LIMITS = { min: 2, max: 16 };
export const COOP_MARKER = '.armahost';
export const coopFolderName = world => `ArmaHost_Coop.${world}`;

// Squad roles in order; slots beyond the list are riflemen. Groups hold at most 8.
const ROLES = ['B_Soldier_TL_F', 'B_medic_F', 'B_soldier_AR_F', 'B_Soldier_F', 'B_soldier_LAT_F', 'B_Soldier_GL_F', 'B_soldier_M_F', 'B_Soldier_F'];

export function validateCoopOptions({ world, slots = 8, zeus = true, arsenal = true } = {}) {
  const entry = COOP_WORLDS.find(w => w.world === world);
  if (!entry) throw new Error(`Choose a map: ${COOP_WORLDS.map(w => w.label).join(', ')}.`);
  if (!Number.isInteger(slots) || slots < COOP_LIMITS.min || slots > COOP_LIMITS.max) throw new Error(`Players must be a whole number from ${COOP_LIMITS.min} to ${COOP_LIMITS.max}.`);
  return { world: entry.world, label: entry.label, slots, zeus: zeus === true, arsenal: arsenal === true };
}

function missionSqm({ world, label, slots }) {
  const groups = [];
  for (let left = slots; left > 0; left -= 8) groups.push(Math.min(8, left));
  let id = 0;
  const groupItems = groups.map((count, g) => {
    const groupId = id++;
    const units = Array.from({ length: count }, (_, i) => {
      const unitId = id++;
      // Temporary position: initPlayerLocal.sqf moves everyone to the start point the server picks.
      const x = 500 + g * 6 + i * 2, y = 500 + g * 6;
      return `				class Item${i}
				{
					dataType="Object";
					class PositionInfo
					{
						position[]={${x},0,${y}};
					};
					side="West";
					flags=${i === 0 ? 7 : 5};
					class Attributes
					{
						isPlayable=1;
					};
					id=${unitId};
					type="${ROLES[i] || 'B_Soldier_F'}";
				};`;
    });
    return `		class Item${g}
		{
			dataType="Group";
			side="West";
			class Entities
			{
				items=${count};
${units.join('\n')}
			};
			class Attributes
			{
			};
			id=${groupId};
		};`;
  });
  return `version=54;
class EditorData
{
	moveGridStep=1;
	angleGridStep=0.2617994;
	scaleGridStep=1;
	autoGroupingDist=10;
	toggles=1;
	class ItemIDProvider
	{
		nextID=${id};
	};
};
binarizationWanted=0;
sourceName="ArmaHost_Coop";
addons[]=
{
	"A3_Characters_F"
};
class AddonsMetaData
{
	class List
	{
		items=1;
		class Item0
		{
			className="A3_Characters_F";
			name="Arma 3 - Characters and Clothing";
			author="Bohemia Interactive";
			url="https://www.arma3.com";
		};
	};
};
randomSeed=1337;
class ScenarioData
{
	author="ArmaHost";
	overviewText="Co-op sandbox on ${label}. The admin builds the action with Zeus.";
};
class Mission
{
	class Intel
	{
		briefingName="ArmaHost Co-op (${label})";
		overviewText="Co-op sandbox. Log in as admin (#login) and press Y for Zeus.";
		timeOfChanges=1800.0002;
		startWeather=0.25;
		startWind=0.1;
		startWaves=0.1;
		forecastWeather=0.25;
		forecastWind=0.1;
		forecastWaves=0.1;
		forecastLightnings=0.1;
		year=2035;
		month=6;
		day=24;
		hour=8;
		minute=0;
		startFogDecay=0.014;
		forecastFogDecay=0.014;
	};
	class Entities
	{
		items=${groups.length};
${groupItems.join('\n')}
	};
};
`;
}

function descriptionExt({ label, slots }) {
  return `// ArmaHost co-op starter (${label}). Generated by ArmaHost Desktop; safe to edit.
author = "ArmaHost";
onLoadName = "ArmaHost Co-op (${label})";
onLoadMission = "Co-op sandbox. Log in as admin (#login) and press Y for Zeus.";
class Header
{
    gameType = Coop;
    minPlayers = 1;
    maxPlayers = ${slots};
};
respawn = 3;
respawnDelay = 15;
respawnOnStart = -1;
respawnDialog = 0;
disabledAI = 1;
joinUnassigned = 1;
briefing = 0;
debriefing = 0;
enableDebugConsole = 1;
`;
}

function initServer({ zeus, arsenal }) {
  return `// ArmaHost co-op starter: picks a safe start point on any terrain, then sets up the respawn
// point${arsenal ? ', an Arsenal crate' : ''}${zeus ? ' and Zeus for whoever is logged in as admin' : ''}.
private _ws = worldSize;
private _centre = [_ws / 2, _ws / 2, 0];
private _places = nearestLocations [_centre, ["Airport"], _ws];
if (_places isEqualTo []) then { _places = nearestLocations [_centre, ["NameCityCapital", "NameCity", "NameVillage"], _ws]; };
private _anchor = if (_places isEqualTo []) then { _centre } else { locationPosition (_places select 0) };
private _start = [_anchor, 0, 300, 8, 0, 0.25, 0, [], [_anchor, _anchor]] call BIS_fnc_findSafePos;
if (count _start < 2) then { _start = _anchor; };
_start = [_start select 0, _start select 1, 0];
ARMAHOST_start = _start;
publicVariable "ARMAHOST_start";
private _marker = createMarker ["respawn_west", _start];
_marker setMarkerType "respawn_inf";
_marker setMarkerText "Base";

ARMAHOST_box = objNull;
${arsenal ? `ARMAHOST_box = createVehicle ["B_supplyCrate_F", _start getPos [10, 45], [], 0, "NONE"];
ARMAHOST_box allowDamage false;
` : ''}publicVariable "ARMAHOST_box";
${zeus ? `
// Zeus: one curator, handed to whoever is logged in as admin and taken back when they log out.
ARMAHOST_curator = (createGroup sideLogic) createUnit ["ModuleCurator_F", [0, 0, 0], [], 0, "NONE"];
ARMAHOST_curator setVariable ["Addons", 3, true];
ARMAHOST_curator setVariable ["Forced", 0, true];
ARMAHOST_curator setVariable ["Name", "Zeus", true];
ARMAHOST_curator addCuratorAddons activatedAddons;
[] spawn {
    while {true} do {
        private _curator = ARMAHOST_curator;
        private _owner = getAssignedCuratorUnit _curator;
        if (!isNull _owner && {admin (owner _owner) == 0}) then { unassignCurator _curator; _owner = objNull; };
        if (isNull _owner) then {
            { if (admin (owner _x) > 0) exitWith { _x assignCurator _curator; }; } forEach allPlayers;
        };
        private _new = (allUnits + vehicles) select { !(_x in curatorEditableObjects _curator) };
        if (count _new > 0) then { _curator addCuratorEditableObjects [_new, true]; };
        sleep 5;
    };
};
` : ''}`;
}

function initPlayerLocal({ zeus, arsenal }) {
  return `// ArmaHost co-op starter: move the player to the start point the server picked.
waitUntil { !isNil "ARMAHOST_start" && {!isNull player} };
private _spot = ARMAHOST_start getPos [3 + random 12, random 360];
player setPosATL [_spot select 0, _spot select 1, 0];
${arsenal ? `waitUntil { !isNil "ARMAHOST_box" };
if (!isNull ARMAHOST_box) then {
    ARMAHOST_box addAction ["<t color='#c3e783'>Arsenal</t>", { ["Open", true] spawn BIS_fnc_arsenal; }, nil, 6, true, true, "", "true", 6];
};
` : ''}systemChat "ArmaHost co-op: you start at the base marker. Respawn is 15 seconds.";
${zeus ? `systemChat "Admin: type #login in chat, then press Y for Zeus to spawn enemies, objectives and vehicles.";
` : ''}`;
}

export function buildCoopMission(options) {
  const o = validateCoopOptions(options);
  return {
    folderName: coopFolderName(o.world), world: o.world, label: o.label,
    files: {
      'mission.sqm': missionSqm(o), 'description.ext': descriptionExt(o),
      'initServer.sqf': initServer(o), 'initPlayerLocal.sqf': initPlayerLocal(o),
      [COOP_MARKER]: `Created by ArmaHost Desktop. ArmaHost may replace this folder when you recreate the co-op starter.\n${JSON.stringify({ world: o.world, slots: o.slots, zeus: o.zeus, arsenal: o.arsenal })}\n`
    }
  };
}

// Writes the mission into <server folder>\MPMissions. A folder without ArmaHost's marker is never touched.
export async function writeCoopMission(serverExe, options) {
  if (!serverExe) throw new Error('Choose the dedicated server executable in Setup and save first.');
  const mission = buildCoopMission(options);
  const folder = path.join(path.dirname(serverExe), 'MPMissions', mission.folderName);
  let exists = false;
  try { exists = (await stat(folder)).isDirectory(); } catch { /* New folder. */ }
  if (exists) {
    const marker = await readFile(path.join(folder, COOP_MARKER), 'utf8').catch(() => null);
    if (marker === null) throw new Error(`${mission.folderName} already exists in MPMissions and wasn't made by ArmaHost, so it was left alone. Rename or remove it first.`);
  }
  await mkdir(folder, { recursive: true });
  for (const [name, content] of Object.entries(mission.files)) await writeFile(path.join(folder, name), content);
  return { template: mission.folderName, folder, label: mission.label };
}
