import { mkdir, writeFile, rename, unlink } from 'node:fs/promises';
import path from 'node:path';
import { packPbo } from './pbo.mjs';

// Server-only addon generated by ArmaHost for the Live map. It runs only on the dedicated server
// (loaded through -serverMod; the script also exits unless isServer) and writes compact position
// frames to the server's RPT with diag_log, which ArmaHost already tails. Nothing is sent to players.
export const MAP_PREFIX = 'armahost_map';
export const LIMITS = { units: 600, vehicles: 300, markers: 300 };

export const CONFIG_CPP = `class CfgPatches
{
    class armahost_map
    {
        name = "ArmaHost Live Map (server only)";
        author = "ArmaHost";
        units[] = {};
        weapons[] = {};
        requiredVersion = 2.0;
        requiredAddons[] = {"A3_Functions_F"};
    };
};
class CfgFunctions
{
    class ArmaHost
    {
        tag = "ARMAHOST";
        class Map
        {
            file = "\\armahost_map\\functions";
            class feed { postInit = 1; };
        };
    };
};
`;

export function feedScript(interval) {
  if (!Number.isInteger(interval) || interval < 2 || interval > 30) throw new Error('Live map interval must be 2-30 seconds.');
  return `// ArmaHost Live Map feed. Server only; read-only; writes AHMAP lines to the RPT.
if (!isServer) exitWith {};
if (!isNil "ARMAHOST_mapFeed") exitWith {};
ARMAHOST_mapFeed = true;
[] spawn {
    private _base = ${interval};
    private _interval = _base;
    private _seq = 0;
    private _bad = "|^~""" + toString [10, 13];
    private _clean = { ((_this splitString _bad) joinString " ") select [0, 60] };
    private _int = { (round _this) toFixed 0 };
    private _emit = {
        params ["_kind", "_records"];
        private _line = "";
        {
            if (_line != "" && {count _line + count _x > 900}) then {
                diag_log text ("AHMAP|" + _kind + "|" + (_seq toFixed 0) + "|" + _line);
                _line = "";
            };
            _line = [_line + "^" + _x, _x] select (_line == "");
        } forEach _records;
        if (_line != "") then { diag_log text ("AHMAP|" + _kind + "|" + (_seq toFixed 0) + "|" + _line); };
    };
    private _display = { (getText (configFile >> "CfgVehicles" >> typeOf _this >> "displayName")) call _clean };
    while {true} do {
        _seq = _seq + 1;
        private _units = allUnits select [0, ${LIMITS.units}];
        private _vehicles = (vehicles select {_x isKindOf "AllVehicles"}) select [0, ${LIMITS.vehicles}];
        private _markers = (allMapMarkers select {markerShape _x != "POLYLINE"}) select [0, ${LIMITS.markers}];
        diag_log text ("AHMAP|F|" + (_seq toFixed 0) + "|" + (time call _int) + "|" + (worldName call _clean) + "|" + (worldSize call _int) + "|" + (_interval toFixed 0) + "|" + ((getText (configFile >> "CfgWorlds" >> worldName >> "pictureMap")) call _clean));
        ["U", _units apply {
            private _p = getPosWorld _x;
            private _v = vehicle _x;
            [(name _x) call _clean, str side group _x, (_p select 0) call _int, (_p select 1) call _int, (getDir _x) call _int,
             ["0", "1"] select (isPlayer _x), ["", _v call _display] select (_v != _x), (groupId group _x) call _clean] joinString "~"
        }] call _emit;
        ["V", _vehicles apply {
            private _p = getPosWorld _x;
            [_x call _display, str side _x, (_p select 0) call _int, (_p select 1) call _int, (getDir _x) call _int,
             (count crew _x) toFixed 0, ["0", "1"] select (alive _x), (typeOf _x) call _clean] joinString "~"
        }] call _emit;
        ["M", _markers apply {
            private _p = markerPos _x;
            private _s = markerSize _x;
            [_x call _clean, (markerText _x) call _clean, (markerType _x) call _clean, (markerColor _x) call _clean, (markerShape _x) call _clean,
             (_p select 0) call _int, (_p select 1) call _int, (_s select 0) call _int, (_s select 1) call _int,
             (markerDir _x) call _int, (markerAlpha _x) toFixed 2] joinString "~"
        }] call _emit;
        diag_log text ("AHMAP|E|" + (_seq toFixed 0) + "|" + (count _units toFixed 0) + "|" + (count _vehicles toFixed 0) + "|" + (count _markers toFixed 0));
        _interval = [_base, _base max 5] select (count _units + count _vehicles > 300);
        sleep _interval;
    };
};
`;
}

export function buildMapAddon(interval) {
  return packPbo({ 'config.cpp': CONFIG_CPP, 'functions\\fn_feed.sqf': feedScript(interval) }, { prefix: MAP_PREFIX });
}
export async function writeMapAddon(dir, interval) {
  const addons = path.join(dir, 'addons'); await mkdir(addons, { recursive: true });
  const target = path.join(addons, `${MAP_PREFIX}.pbo`); const temporary = `${target}.tmp`;
  try { await writeFile(temporary, buildMapAddon(interval)); await rename(temporary, target); }
  finally { await unlink(temporary).catch(() => {}); }
  return target;
}
